name: Build and Test Task1 Branch

on:
  push:
    branches:
      - task1
  pull_request:
    types: [ opened, synchronize ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Setup Java environment
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache dependencies for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run unit tests
        run: mvn clean test

      - name: Generate Allure report
        run: mvn clean test allure:report

      - name: Archive Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: target/allure-report/*